name: Collect and Upload Package Metadata

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  brew:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Disable Homebrew analytics to avoid inflating install counts
        run: brew analytics off

      - name: Update Homebrew
        run: brew update

      - name: Collect metadata for brew packages
        run: bundle exec ruby scripts/brew/main.rb sources/brew-taps.yaml
        env:
          GOOGLE_CLOUD_PROJECT: getovert
          GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

  scoop:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install scoop
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm get.scoop.sh | iex

      - name: Collect metadata for scoop packages
        run: bundle exec ruby scripts/scoop/main.rb sources/scoop-buckets.yaml
        env:
          GOOGLE_CLOUD_PROJECT: getovert
          GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
